const eventsList = [
  {
		"day_count": 1,
		"type": "session",//capitalize
		"color": "#424242",
		"ticket": "dito_link_sa_ticket",
		"title": "Scrap Art",
    //replace space to underscores for images
    //add to ticket
		"subtitle": "sessions to showcase artworks",
		"number": "1",
		"day": "MON 05.06",
    //add to title with date
    //add to ticket
		"time": "19:00—23:00",
		"description": "artists showcase their works made from everyday objects",
    //capitalize description
		"price": "50",
		"header1": "art made by winnie and sabi",
    //capitalize header1
		"paragr1": "Come to Hain and watch as Winnie Celestine and Sabi Pratik showcase their work as they say how they made it, and why they made it in the first place and explore the artistic mind of these two who turned what used to be scraps of trash to pieces of art.",
    "header2": "\twinnie and sabi say their take on why they use scraps",
		//capitalize header2
		"paragr2": "Winnie Celestine and Sabi Pratik is well known for their art installations derived from scraps, or everyday objects that we don’t often bat an eye to, Sabi Patrik uses Cafeteria reciepts and recipes to make his collages while Winnie Celestine uses discarded food packaging and plastic utensils, which she reconfigure into sculptural installations that blur the lines between art, craft, and design. Their art which inspired artists all over the globe to use foreign materials to create art finally break their silence. come to Hain and watch as Winnie Celestine and Sabi Pratik showcase their art Winnie Celestine and Sabi Pratik is well known for their art installations derived from scraps, or everyday objects that we don’t often bat an eye to, Sabi Patrik uses Cafeteria reciepts and recipes to make his collages while Winnie Celestine uses discarded food packaging and plastic utensils, which she reconfigure into sculptural installations that blur the lines between art, craft, and design. Their art which inspired artists all over the globe to use foreign materials to create art finally break their silence. come to Hain and watch as Winnie Celestine and Sabi Pratik showcase their art "
	},
  {
		"day_count": 1,
		"type": "events",
		"color": "#413327",
		"ticket": "dito_link_sa_ticket",
		"title": "POLYDISPSIA",
		"subtitle": "a series of talks about extreme thirst",
		"number": "2",
		"day": "THU 15.06",
		"time": "18:00—22:00",
		"description": "a session to discuss polydispsia a thing that is frequent in africa",
		"price": "50",
		"header1": "polydipsia: an important health topic in africa",
		"paragr1": "Join us for an informative and engaging session to discuss polydipsia and its impact on health in Africa. Our expert panel will engage in a lively discussion with attendees. Whether you're a healthcare professional, researcher, policymaker, or concerned citizen, this session is a valuable opportunity to learn and contribute to the fight against polydipsia in Africa.",
		"header2": "\tpolydipsia, a condition characterized by excessive thirst",
		"paragr2": "At this informative session, you'll learn about the causes, symptoms, and treatment options for polydipsia. Our expert panel will provide insights into the latest research on this condition, and share practical tips and strategies for managing it effectively. Whether you're a healthcare professional, patient, or concerned citizen, this session is an important opportunity to deepen your understanding of polydipsia and its impact on health in Africa.At this informative session, you'll learn about the causes, symptoms, and treatment options for polydipsia. Our expert panel will provide insights into the latest research on this condition, and share practical tips and strategies for managing it effectively. Whether you're a healthcare professional, patient, or concerned citizen, this session is an important opportunity to deepen your understanding of polydipsia and its impact on health in Africa."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#313324",
		"ticket": "dito_link_sa_ticket",
		"title": "AGRICULTURE",
		"subtitle": "a series of talks about agriculture",
		"number": "3",
		"day": "TUE 20.06",
		"time": "21:00—01:00",
		"description": "a session all about argiculture a part 2 of her last session  ",
		"price": "50",
		"header1": "talks about agriculture",
		"paragr1": "Come to hain and experience this exhibit that is designed to educate and inform visitors about various topics related to agriculture, including farming techniques, sustainability, and the impact of agriculture on the environment.\nyou'll find a series of interactive displays and presentations that showcase the latest advancements in agricultural research and innovation.",
		"header2": "\tall about the history of agriculture and its roots",
		"paragr2": "Here at hain, we strive to provide informational sessions. One of which showcases the journey that food takes from the farm to the consumer's plate. You'll learn about the different stages of food production, including planting, harvesting, and processing, and how these stages impact the nutritional value of our food.\n\nWe will also be showcasing the importance of sustainable farming practices in preserving our environment and natural resources. You'll learn about innovative techniques such as crop rotation, conservation tillage, and integrated pest management.Here at hain, we strive to provide informational sessions. One of which showcases the journey that food takes from the farm to the consumer's plate. You'll learn about the different stages of food production, including planting, harvesting, and processing, and how these stages impact the nutritional value of our food.\n\nWe will also be showcasing the importance of sustainable farming practices in preserving our environment and natural resources. You'll learn about innovative techniques such as crop rotation, conservation tillage, and integrated pest management."
	},
  {
		"day_count": 1,
		"type": "event",
		"color": "#3B2D29",
		"ticket": "dito_link_sa_ticket",
		"title": "WASTE",
		"subtitle": "an event all about wastes and our involvement",
		"number": "4",
		"day": "SUN 25.06",
		"time": "19:00—21:30",
		"description": "why we shouldn’t take our food for granted",
		"price": "50",
		"header1": "waste - finally here in hain",
		"paragr1": "The very popular and well respected movement led by three artists, Winnie Celestine, Chloe Rosales, and Skai Malik finally reaches it’s way to Hain. Watch as Winnie and Chloe say their take on just how much we took for granted our food, and after Skai will do one of his famous performances where he shows the struggles and successes of agriculture and fishery. ",
		"header2": "\tthe history - how this movement started and it’s origins",
		"paragr2": "This movement that these three individuals aren’t the first to do this movement as it goes all the way back since the start of modernization of our civilization, but as waste become more and more cluttered everywhere and we start to feel the effects of just how much we took food and mother nature for granted is when the movement is finally being recognized. These three which are the ones leading this movement shed light on just why the movement started and when the effects of our ingratitude to food and mother nature started.This movement that these three individuals aren’t the first to do this movement as it goes all the way back since the start of modernization of our civilization, but as waste become more and more cluttered everywhere and we start to feel the effects of just how much we took food and mother nature for granted is when the movement is finally being recognized. These three which are the ones leading this movement shed light on just why the movement started and when the effects of our ingratitude to food and mother nature started."
	},
  {
		"day_count": 1,
		"type": "event",
		"color": "#403B3B",
		"ticket": "dito_link_sa_ticket",
		"title": "Winnie Live",
		"subtitle": "an event to show how winnie creates her art",
		"number": "5",
		"day": "FRI 30.06",
		"time": "21:00—____",
		"description": "winnie showcases her art by doing her installation live",
		"price": "50",
		"header1": "live art performance by winnie",
		"paragr1": "Winnie Celestine well known for his cubic art derived from scrap material such as discarded food packaging and plastic utensils. Also well known for her sculpture art installations which she will do live here in Hain. This art installation will stay in Hain until the end of Hain 1. ",
		"header2": "\tfirst ever live art performance by winnie celestine",
		"paragr2": "We approached Winnie Celestine of this proposal for her do her art installation live for everyone to see during development phase of Hain 1. As this is the very first time Winnie Celestine is going to do one of her sculpture installations live, we made sure to listen to any of her requests. Winnie Celestine only had one requests, and is to give her as much time as she can to do her live installation. We agreed, even if it takes days or weeks. Watch as Winnie Celestine does her art installation live from March __ until it is finished.We approached Winnie Celestine of this proposal for her do her art installation live for everyone to see during development phase of Hain 1. As this is the very first time Winnie Celestine is going to do one of her sculpture installations live, we made sure to listen to any of her requests. Winnie Celestine only had one requests, and is to give her as much time as she can to do her live installation. We agreed, even if it takes days or weeks. Watch as Winnie Celestine does her art installation live from March __ until it is finished."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#212121",
		"ticket": "dito_link_sa_ticket",
		"title": "SEED",
		"subtitle": "a series of talks all about seeds",
		"number": "6",
		"day": "SUN 09.07",
		"time": "21:00—00:00",
		"description": "an introduction to the seeds all over the globe",
		"price": "50",
		"header1": "discover the beauty and diversity of seeds",
		"paragr1": "Harvey Trahab, an agricultural archivist, will showcase his curated collection that celebrates the diversity of crops often overlooked in industrial agriculture. Discover the beauty of our agricultural heritage and reconnect with our roots.",
		"header2": "\tpreserving our agricultural heritage: the importance of seed conservation",
		"paragr2": "During the session, Harvey will share his insights on the importance of seed preservation, and how it can help to protect our agricultural heritage. Attendees will also learn about the different types of seeds, their characteristics, and how they have evolved over time. This session provides a unique opportunity for people to reconnect with their roots and appreciate the richness of our agricultural heritage.During the session, Harvey will share his insights on the importance of seed preservation, and how it can help to protect our agricultural heritage. Attendees will also learn about the different types of seeds, their characteristics, and how they have evolved over time. This session provides a unique opportunity for people to reconnect with their roots and appreciate the richness of our agricultural heritage."
	},
  {
		"day_count": 1,
		"type": "workshop",
		"color": "#453A33",
		"ticket": "dito_link_sa_ticket",
		"title": "Palate\nArtistry",
		"subtitle": "revolutionary exploration of edible assembly",
		"number": "7",
		"day": "WED 12.07",
		"time": "21:00—23:00",
		"description": "palate perspectives\n-\nunleashing\nthe art\nof food",
		"price": "50",
		"header1": "taste meets design in an artistic revolution",
		"paragr1": "During the session, Hashem will share his techniques and insights on the art of edible assembly, and how it can be used to elevate the dining experience. Attendees will also learn how to approach food as a canvas for artistic expression and explore the possibilities of creating visually stunning meals that are both delicious and beautiful.",
		"header2": "\tdiscover the transformative power of food design",
		"paragr2": "Attendees will have the opportunity to experience the incredible work of Ahmed Hashem, a graphic designer who transforms the ingredients of a dish into a visual feast. Hashem draws inspiration from his love for food in movies, resulting in bold and vibrant designs that invite the viewer to engage with food in a new way, and opens up new possibilities for culinary creativity. Whether you are a chef, food enthusiast, or simply curious about the art of edible assembly, this session is not to be missed.Attendees will have the opportunity to experience the incredible work of Ahmed Hashem, a graphic designer who transforms the ingredients of a dish into a visual feast. Hashem draws inspiration from his love for food in movies, resulting in bold and vibrant designs that invite the viewer to engage with food in a new way, and opens up new possibilities for culinary creativity. Whether you are a chef, food enthusiast, or simply curious about the art of edible assembly, this session is not to be missed."
	},
  {
		"day_count": 1,
		"type": "workshop",
		"color": "#453A33",
		"ticket": "dito_link_sa_ticket",
		"title": "BARE",
		"subtitle": "a series of talks about how food is made",
		"number": "8",
		"day": "THU 20.07",
		"time": "20:00—23:00",
		"description": "explore how food is made in it’s purest form",
		"price": "50",
		"header1": "bare - food in it’s most purest form",
		"paragr1": "Skai Malik with her knowledge in agriculture and fishing, Ahmed Asham’s depiction of food with it’s bare ingredients, and Harvey Trahab’s knowledge on heirloom crops and seeds, a session of talks where like-minded people say their thoughts on food in it’s barest form.",
		"header2": "\ta gathering for like-minded people to discuss and ask questions",
		"paragr2": "If you are an expert or want to know more about food in it’s most bare, you are invited to this workshop where people discuss the beauty of food aside from when it’s in our plates.\nFood is not all about it’s taste, or when it’s in their complete form. Before it comes to our plates, there are a lot that has already happened. These sessions of talks have people who can appreciate food not how it tastes, but in how it’s made, from seeds, to grown crops, to recipes. Come and participate in these sessions of talks that appreciates not the food itself but the process in how it’s made.If you are an expert or want to know more about food in it’s most bare, you are invited to this workshop where people discuss the beauty of food aside from when it’s in our plates.\nFood is not all about it’s taste, or when it’s in their complete form. Before it comes to our plates, there are a lot that has already happened. These sessions of talks have people who can appreciate food not how it tastes, but in how it’s made, from seeds, to grown crops, to recipes. Come and participate in these sessions of talks that appreciates not the food itself but the process in how it’s made."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#413D27",
		"ticket": "dito_link_sa_ticket",
		"title": "Thrown\nRecipes",
		"subtitle": "a series of talks that talks about thrown recipes",
		"number": "9",
		"day": "SUN 23.07",
		"time": "21:00—00:00",
		"description": "sabi pratik sheds light on history’s thrown recipes",
		"price": "50",
		"header1": "a journey through time and culture",
		"paragr1": "In this session, Sabi Pratik sheds light on the fascinating world of \"thrown food,\" or the recipes that have been discarded and forgotten throughout history. Through their unique collages, Sabi Pratik invites viewers to explore the rich cultural and culinary heritage of these lost recipes and to reflect on the role that food plays in shaping our identity and culture.",
		"header2": "\tuncovering the secrets of thrown recipes with unique collages",
		"paragr2": "This session will take the audience on a journey of discovery as they explore the theme of thrown recipes through a collection of captivating collages. With each piece, Sabi Pratik will guide the audience through an examination of discarded recipes from various cultures and time periods, uncovering the stories behind them and the reasons why they were discarded. This session will take the audience on a journey of discovery as they explore the theme of thrown recipes through a collection of captivating collages. With each piece, Sabi Pratik will guide the audience through an examination of discarded recipes from various cultures and time periods, uncovering the stories behind them and the reasons why they were discarded. "
	},
  {
		"day_count": 1,
		"type": "event",
		"color": "#413327",
		"ticket": "dito_link_sa_ticket",
		"title": "Drink\nGathered",
		"subtitle": "an event to showcase different beverages",
		"number": "10",
		"day": "TUE 28.07",
		"time": "20:00—01:30",
		"description": "an event to gather people to experience all kinds of beverages",
		"price": "50",
		"header1": "discover a world of beverages!",
		"paragr1": "Step into a world of thirst-quenching delights at our immersive event, featuring the incredible work of artist Chloe Rosales. Her powerful photographs explore the fascinating relationship between thirst and social inequality, offering a unique perspective on this universal experience. As you journey through the exhibition, you'll discover the diverse ways in which thirst is perceived and experienced across different cultures and classes.",
		"header2": "\ttasting the world, one beverage at a time",
		"paragr2": "But that's not all – we're also offering an interactive tasting experience that lets you sample a wide range of refreshing and delicious beverages from around the world. From exotic teas to zesty fruit drinks, there's something for every taste and preference. You'll have the opportunity to learn about the unique ingredients, techniques, and cultural traditions that go into making each beverage, and gain a deeper appreciation for the rich tapestry of global drinking culture.But that's not all – we're also offering an interactive tasting experience that lets you sample a wide range of refreshing and delicious beverages from around the world. From exotic teas to zesty fruit drinks, there's something for every taste and preference. You'll have the opportunity to learn about the unique ingredients, techniques, and cultural traditions that go into making each beverage, and gain a deeper appreciation for the rich tapestry of global drinking culture."
	},
  {
		"day_count": 1,
		"type": "event",
		"color": "#212121",
		"ticket": "dito_link_sa_ticket",
		"title": "All Smell",
		"subtitle": "an event about spices",
		"number": "11",
		"day": "TUE 01.08",
		"time": "21:00—00:00",
		"description": "experience the beauty of spices blindfolded",
		"price": "50",
		"header1": "all smell - by harvey trahab",
		"paragr1": "Harvey Trahab, one of the most renowned and creative artists with his unique ways of letting people experience his work is now here in Hain and will be doing one of his famous exhibitions.\nA space will be given to Harvey Trahab this Tuesday to experience “All Smell” where people will enter a room blindfolded and is allowed to only smell their surroundings.",
		"header2": "\texperience culture through smell",
		"paragr2": "Harvey Trahab has traveled all over the globe and has grown familiar of the different heirloom seeds and crops. One thing is apparent whenever he travels to a country and study their heirloom crops. The smell. A country’s spices, even without researching is very apparent and you can easily differentiate it through smell. Harvey Trahab wishes to let people experience this by letting people go in different rooms with different spices from different countries to hopefully let people experience the beauty of the heirloom crops in those respective countries.Harvey Trahab has traveled all over the globe and has grown familiar of the different heirloom seeds and crops. One thing is apparent whenever he travels to a country and study their heirloom crops. The smell. A country’s spices, even without researching is very apparent and you can easily differentiate it through smell. Harvey Trahab wishes to let people experience this by letting people go in different rooms with different spices from different countries to hopefully let people experience the beauty of the heirloom crops in those respective countries."
	},
  {
		"day_count": 1,
		"type": "workshop",
		"color": "#453A33",
		"ticket": "dito_link_sa_ticket",
		"title": "Eyes\non Flavor",
		"subtitle": "evocative food and transformative vision",
		"number": "12",
		"day": "SAT 05.08",
		"time": "20:00—22:00",
		"description": "culinary design: feasting with the eyes",
		"price": "50",
		"header1": "discover the art of food assembly",
		"paragr1": "Ahmed Hashem will be showcasing his graphic design work. With his passion for food and inspiration from movies, Hashem's designs skillfully transform ingredients into a visual feast.",
		"header2": "\tsee flavor in a whole new light with ahmed hashem",
		"paragr2": "If you are an expert or want to know more about food in it’s most bare, you are invited to this workshop where people discuss the beauty of food aside from when it’s in our plates.\nFood is not all about it’s taste, or when it’s in their complete form. Before it comes to our plates, there are a lot that has already happened. These sessions of talks have people who can appreciate food not how it tastes, but in how it’s made, from seeds, to grown crops, to recipes. Come and participate in these sessions of talks that appreciates not the food itself but the process in how it’s made.If you are an expert or want to know more about food in it’s most bare, you are invited to this workshop where people discuss the beauty of food aside from when it’s in our plates.\nFood is not all about it’s taste, or when it’s in their complete form. Before it comes to our plates, there are a lot that has already happened. These sessions of talks have people who can appreciate food not how it tastes, but in how it’s made, from seeds, to grown crops, to recipes. Come and participate in these sessions of talks that appreciates not the food itself but the process in how it’s made."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#3B3929",
		"ticket": "dito_link_sa_ticket",
		"title": "WORD",
		"subtitle": "a series of talks about words, namely about food",
		"number": "13",
		"day": "SUN 08.08",
		"time": "20:00—22:30",
		"description": "exploring non-appetizing words, and the beauty of it",
		"price": "50",
		"header1": "a journey of words and food",
		"paragr1": "In this session, Sue Dolores will guide you through a journey of discovery, where you'll learn about the power of words and how they shape our perception of food. You'll also have the opportunity to create your own food-related poems and wordplay, using culinary jargon and other fun and interesting language. Don't miss this chance to explore the delicious world of words with one of the most talented and passionate food writers around.",
		"header2": "\tdiscover the history and origin of food-related words",
		"paragr2": "Through a series of talks and activities, you'll discover the history and origin of food-related words, and learn how to use them to create your own unique culinary vocabulary. Whether you're a food lover, a language enthusiast, or just looking for a fun and engaging way to spend your time, this session is sure to be a delight for your senses and your mind.Through a series of talks and activities, you'll discover the history and origin of food-related words, and learn how to use them to create your own unique culinary vocabulary. Whether you're a food lover, a language enthusiast, or just looking for a fun and engaging way to spend your time, this session is sure to be a delight for your senses and your mind."
	},
  {
		"day_count": 1,
		"type": "workshop",
		"color": "#404A4D",
		"ticket": "dito_link_sa_ticket",
		"title": "Lecture\nNight",
		"subtitle": "a workshop that teaches people how to write",
		"number": "14",
		"day": "SUN 13.08",
		"time": "19:00—22:00",
		"description": "sue dolores teaches how to write",
		"price": "50",
		"header1": "discover the art of food writing",
		"paragr1": "Join us for a unique writing workshop with renowned food writer Sue Dolores. In this session, Sue will guide you through the process of crafting compelling and engaging food writing. Whether you're an experienced writer or just starting out, Sue's insights and expertise will help you take your writing to the next level.",
		"header2": "\tbring your passion for food to life on the page",
		"paragr2": "Through a series of interactive exercises and discussions, you'll learn how to bring your passion for food to life on the page. Sue will share tips and tricks for finding inspiration, developing your voice, and creating vivid and descriptive scenes that transport your readers to the world of food.\n\nBy the end of the workshop, you'll have a better understanding of the art and craft of food writing, as well as the skills and confidence to continue honing your craft. Don't miss this chance to learn from one of the most talented and passionate food writers in the industry.Through a series of interactive exercises and discussions, you'll learn how to bring your passion for food to life on the page. Sue will share tips and tricks for finding inspiration, developing your voice, and creating vivid and descriptive scenes that transport your readers to the world of food.\n\nBy the end of the workshop, you'll have a better understanding of the art and craft of food writing, as well as the skills and confidence to continue honing your craft. Don't miss this chance to learn from one of the most talented and passionate food writers in the industry."
	},
  {
		"day_count": 1,
		"type": "event",
		"color": "#4E4E4E",
		"ticket": "dito_link_sa_ticket",
		"title": "Poetry\nNight",
		"subtitle": "event to share each other’s poetry",
		"number": "15",
		"day": "TUE 15.08",
		"time": "21:00—00:30",
		"description": "a gathering of like-minded people to share their work",
		"price": "50",
		"header1": "indulge in a night of food and poetry",
		"paragr1": "Join us for an evening of thought-provoking, heartfelt, and entertaining spoken word performances that explore the diverse and delicious world of food. Poets from around the world will take you on a journey across continents and cultures, sharing their personal experiences and reflections on food.",
		"header2": "\tsavor the flavors of poetry and food from around the world",
		"paragr2": "From savory to sweet, from street food to haute cuisine, from childhood memories to adult cravings, our poets will use the universal language of poetry to capture the joys, sorrows, and complexities of our relationship with food. You'll be transported to different parts of the world, immersed in the sights, sounds, and smells of different culinary traditions, and moved by the personal stories and perspectives of our talented poets.\n\nWhether you're a seasoned poetry lover or new to the world of spoken word, this event is sure to be a memorable and meaningful experience. So come join us for a night of poetry and food, and discover the world in a whole new way.From savory to sweet, from street food to haute cuisine, from childhood memories to adult cravings, our poets will use the universal language of poetry to capture the joys, sorrows, and complexities of our relationship with food. You'll be transported to different parts of the world, immersed in the sights, sounds, and smells of different culinary traditions, and moved by the personal stories and perspectives of our talented poets.\n\nWhether you're a seasoned poetry lover or new to the world of spoken word, this event is sure to be a memorable and meaningful experience. So come join us for a night of poetry and food, and discover the world in a whole new way."
	},
  {
		"day_count": 1,
		"type": "workshop",
		"color": "#3B2929",
		"ticket": "dito_link_sa_ticket",
		"title": "KITCHEN",
		"subtitle": "a series of talks all about kitchens",
		"number": "16",
		"day": "SAT 19.08",
		"time": "19:00—21:00",
		"description": "explore the different ways people cook with bernice rowe",
		"price": "50",
		"header1": "kitchen - where all of it is made",
		"paragr1": "Bernice Rowe with her interesting photography of Kitchens all around the world, she shows the intimacy that should be felt, not when eating food, and not how it is made, but rather what is used to create the food that end up on our plates. Bernice Rowe depicts one’s culture with her photography by showing equipment used for cooking which varies a lot from culture to culture.",
		"header2": "\t“one’s kitchen shows one’s culture”\n- bernice rowe",
		"paragr2": "From the quote above, when you see a kitchen you can almost name at least which continent that kitchen resides in. It’s easy to distinct the kitchen from Asia to Europe, and it’s easy to distinct a kitchen from Vietnam to an American Kitchen, the thing is people often know which country or continent one’s kitchen is from but never really dig deeper than this.\nBernice Rowe will be showing her work and saying her experiences going all around the globe to photograph different kitchens and share her thoughts in hopes that people view kitchens in a new light.From the quote above, when you see a kitchen you can almost name at least which continent that kitchen resides in. It’s easy to distinct the kitchen from Asia to Europe, and it’s easy to distinct a kitchen from Vietnam to an American Kitchen, the thing is people often know which country or continent one’s kitchen is from but never really dig deeper than this.\nBernice Rowe will be showing her work and saying her experiences going all around the globe to photograph different kitchens and share her thoughts in hopes that people view kitchens in a new light."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#413227",
		"ticket": "dito_link_sa_ticket",
		"title": "The Culture of Gatherings",
		"subtitle": "a series of talks about the culture that loves gatherings",
		"number": "17",
		"day": "TUE 22.08",
		"time": "21:00—23:30",
		"description": "exploring the dining culture of the south east asian countries",
		"price": "50",
		"header1": "exploring the dining culture of southeast asia",
		"paragr1": "Join Ronaldo for a thought-provoking session that explores the diverse and flavorful dining cultures of Southeast Asia. Ronaldo is a chef and food expert who has a passion for sharing his knowledge and experiences with others. Through his engaging and informative talk, you'll discover the rich cultural heritage of Southeast Asian cuisine and learn about the history and significance of each dish.",
		"header2": "\ta journey through southeast asia's dining culture",
		"paragr2": "During the session, Ronaldo will share stories about his travels through Southeast Asia and the various culinary traditions he has encountered. You'll also have the chance to learn about the different ingredients and techniques used in Southeast Asian cooking, as well as tips for cooking and enjoying authentic dishes. Ronaldo's lively personality and passion for food will inspire you to explore new flavors and experiences.During the session, Ronaldo will share stories about his travels through Southeast Asia and the various culinary traditions he has encountered. You'll also have the chance to learn about the different ingredients and techniques used in Southeast Asian cooking, as well as tips for cooking and enjoying authentic dishes. Ronaldo's lively personality and passion for food will inspire you to explore new flavors and experiences."
	},
  {
		"day_count": 7,
		"type": "event",
		"color": "#412727",
		"ticket": "dito_link_sa_ticket",
		"title": "First-Hand\nFiesta",
		"subtitle": "an event to experience the south east asian fiesta",
		"number": "18",
		"day": "THU 24.08",
		"time": "21:00—7 DAYS",
		"description": "experience a big food gathering that is not grand ",
		"price": "50",
		"header1": "first-hand fiesta",
		"paragr1": "After the sessions of talks that Ronaldo Alfonso did naming south-east Asian countries the the culture of gatherings, Ronaldo Alfonso wants to let people experience the fiesta, where the gatherings of people is to the most extreme.",
		"header2": "\tan event to experience\nthe mother of all gatherings",
		"paragr2": "As Ronaldo Alfonso dubbed south-east Asian countries the culture of gatherings, of all of the times where people are gathered for food, the time where people are gathered that reaches to the hundreds especially in south-east Asian countries is during a Fiesta. In these fiesta there’s a very long table that is just filled with food, and everyone in the neighborhood are invited to eat. Ronaldo Alfonso wanted to let people outside of south-east Asia to experience this, and so Hain will make itself fiesta themed for 1 week, that can house more than a hundred people. Join us in this fiesta themed week of Hain where you can have a first-hand intimate experience of the most grand culture of gatherings in the world, which is a fiesta.As Ronaldo Alfonso dubbed south-east Asian countries the culture of gatherings, of all of the times where people are gathered for food, the time where people are gathered that reaches to the hundreds especially in south-east Asian countries is during a Fiesta. In these fiesta there’s a very long table that is just filled with food, and everyone in the neighborhood are invited to eat. Ronaldo Alfonso wanted to let people outside of south-east Asia to experience this, and so Hain will make itself fiesta themed for 1 week, that can house more than a hundred people. Join us in this fiesta themed week of Hain where you can have a first-hand intimate experience of the most grand culture of gatherings in the world, which is a fiesta."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#412727",
		"ticket": "dito_link_sa_ticket",
		"title": "Night\nMarket",
		"subtitle": "the melodic market at night",
		"number": "19",
		"day": "MON 28.08",
		"time": "21:00—01:00",
		"description": "a session to discuss the history of night markets around the world",
		"price": "50",
		"header1": "a global exploration of street food culture",
		"paragr1": "Join us for a fascinating session that delves into the rich history of night markets around the world. Through captivating discussions and interactive activities, we will explore the cultural significance of night markets and their impact on communities.",
		"header2": "\tdiscover the rich history of night markets around the world",
		"paragr2": "The featured artist, Peter Chan, will showcase his latest work, which offers a unique perspective on street food markets. Using the iPhone live feature, Chan has captured the sounds of bustling night markets, immersing the audience in the vibrant atmosphere of these markets. Through his work, we will gain a deeper understanding of the emotional and cultural connections that people have with street food and night markets. Don't miss this chance to experience the world of night markets like never before.The featured artist, Peter Chan, will showcase his latest work, which offers a unique perspective on street food markets. Using the iPhone live feature, Chan has captured the sounds of bustling night markets, immersing the audience in the vibrant atmosphere of these markets. Through his work, we will gain a deeper understanding of the emotional and cultural connections that people have with street food and night markets. Don't miss this chance to experience the world of night markets like never before."
	},
  {
		"day_count": 1,
		"type": "session",
		"color": "#35352A",
		"ticket": "dito_link_sa_ticket",
		"title": "Street\nFood",
		"subtitle": "a session of talks about street food",
		"number": "20",
		"day": "WED 12.08",
		"time": "21:00—01:30",
		"description": "explore the subtle things in all the noise in the streets",
		"price": "50",
		"header1": "street food - where one’s culture is apparent",
		"paragr1": "With four renowned artist, Ronaldo Alfonso, Bernice Rowe, Sabi Pratik, and Peter Chan, with their experiences with different kinds of food from different cultures all over the globe, join them as they say their experiences, show their artworks, and join them as they converse about street food, where one’s culture is most visible. ",
		"header2": "\tsubtleties in all of the noise that we hear from the streets",
		"paragr2": "The artists gathered are people that aside from focusing on the food itself, everyone invited are people that enjoy the things often overlooked. Ronaldo Alfonso catches the intimate scenery of people enjoying their food with his photography, Peter Chan takes photographs of streets bustling with people and food and recording audio to immerse a person in it’s pictures. Bernice Rowe takes pictures of different kitchens all around the globe, highlighting the distinct tools and cooking practices that shape the culinary traditions of different cultures, and Sabi Pratik collects everyday items to make collages to show the beauty things we often overlook.The artists gathered are people that aside from focusing on the food itself, everyone invited are people that enjoy the things often overlooked. Ronaldo Alfonso catches the intimate scenery of people enjoying their food with his photography, Peter Chan takes photographs of streets bustling with people and food and recording audio to immerse a person in it’s pictures. Bernice Rowe takes pictures of different kitchens all around the globe, highlighting the distinct tools and cooking practices that shape the culinary traditions of different cultures, and Sabi Pratik collects everyday items to make collages to show the beauty things we often overlook."
	}
];