const soundbitesList = [
  {
    "file": "sb1",
    "type": "small",
    "title": "I Salt My Avocado",
    "description": "An intimate story between multiple generations of a community sharing tradition through food, stories, and livelihood.",
    "time": "May 29—June 4",
    "images": [
      { "time": "0", "data": "1" },
      { "time": "14", "data": "2" },
      { "time": "44", "data": "3" },
      { "time": "67", "data": "4" },
      { "time": "93", "data": "5" },
      { "time": "108", "data": "" }
    ],
    "texts": [
      { "time": "0", "data": "I wrote a poem almost a year ago," },
      { "time": "4", "data": "reimagining my mother’s story of my great-grandfather" },
      { "time": "10", "data": "at the height of the Japanese occupation of the Philippines" },
      { "time": "14", "data": "Feeding on a beached whale, in some obscure shoreline. " },
      { "time": "20", "data": "I imagine the redwood, its invitation to him. " },
      { "time": "25", "data": "The call of America in the guise of Filipino patriotism." },
      { "time": "32", "data": "This subtle call from far away. Sealed by a beached whale." },
      { "time": "40", "data": "A nourishing promise." },
      { "time": "44", "data": "When my was in high-school my great-grandfather promised he’d return from America." },
      { "time": "51", "data": "My mother’s tongue is as sharp as her memory." },
      { "time": "55", "data": "Crowded with dreams of ginger and capsaicin." },
      { "time": "61", "data": "As if calling my great-grandfather to return." },
      { "time": "67", "data": "And he did return." },
      { "time": "70", "data": "However, the avocado at the backyard has ripen again." },
      { "time": "77", "data": "The air was salty maybe from tears or the shore." },
      { "time": "82", "data": "My mother has arrived herself. My mother" },
      { "time": "88", "data": "A wasp bites her yet she cusses smoother than honey." },
      { "time": "93", "data": "My ‘papa’ as she calls my great-grandfather." },
      { "time": "99", "data": "When he passed, smoother than honey, my mother " },
      { "time": "103", "data": "pleads to demand what happens after the world ends. " },
      { "time": "108", "data": "I think of a nourishing promise," },
      { "time": "112", "data": "the swelling of a beached whale, " },
      { "time": "115", "data": "the feast my great-grandfather partook in, " },
      { "time": "120", "data": "and the satisfaction of hunger by an answer." },
      { "time": "125", "data": "I think of her putting ‘too much’ chili powder," },
      { "time": "128", "data": "‘too much’  ginger on any plate imaginable." },
      { "time": "133", "data": "I think of smiling through the ginger bits stuck in my teeth, scratching my throat." },
      { "time": "140", "data": "The chili powder that blushes me red," },
      { "time": "144", "data": "and to salt my avocado, even after the world ends." }
    ]
  },
  {
    "file": "sb2",
    "type": "small",
    "title": "Kitchens: A Narrative",
    "description": "Bernice Rowe recounts the personal narratives tucked behind her camera lens on a narrative edition of <i>Kitchens<i>",
    "time": "June 5—11",
    "images": [
      { "time": "0", "data": "" },
      { "time": "18", "data": "1" },
      { "time": "40", "data": "2" },
      { "time": "60", "data": "3" },
      { "time": "80", "data": "4" },
      { "time": "91", "data": "" }
    ],
    "texts": [
      { "time": "0", "data": "No matter the reason for the differences," },
      { "time": "3", "data": "all these photos of kitchens around the world show the ingenuity," },
      { "time": "6", "data": "adaptability and diversity of humankind." },
      { "time": "10", "data": "And from each kitchen comes a unique story" },
      { "time": "13", "data": "of the family who cooks, gathers and cleans there." },
      { "time": "18", "data": "Here, Abdoul adds corn flour to a meal that his sister, Adèle, is cooking in their outdoor kitchen. " },
      { "time": "25", "data": "They cook over coals on a simple stove outside their home in Burkina Faso. " },
      { "time": "30", "data": "The food they're cooking was provided by the staff from Adèle's Compassion center, " },
      { "time": "34", "data": "who learned that the family had run out of food during the country's COVID-19 quarantine." },
      { "time": "40", "data": "Here, Leydy, 8, helps her mother cook vegetables in the kitchen of their home in Ecuador. " },
      { "time": "46", "data": "Corn is one of the family’s staple foods, " },
      { "time": "49", "data": "and their home has rows of colorful husks hanging from the ceiling. " },
      { "time": "54", "data": "As is typical in developing countries, the kitchen shares a common space with the living and sleeping areas." },
      { "time": "60", "data": "This is the kitchen where Elianora cooks for her seven children and her husband in rural Indonesia." },
      { "time": "67", "data": "Her husband works as a farmer for a local landowner. " },
      { "time": "71", "data": "When there’s not enough work on the farm, he looks for construction jobs in their village to avoid the heartbreak of seeing his children go to bed hungry." },
      { "time": "80", "data": "While cooking in her kitchen in Bangladesh, Suku holds her toddler, Prodip. " },
      { "time": "86", "data": "With no electricity in the home, Suku relies on the fire pit to cook her daily meal." },
      { "time": "91", "data": "Every kitchen tells a story. From my various travels, these intimate images captured show the remarkable ways that families — usually women or children — cook their food, gather with loved ones to eat it, and organize their kitchens." }
    ]
  },
  {
    "file": "sb3",
    "type": "full",
    "title": "Roots: An Excerpt",
    "description": "Harvey Trahab reads the opening passages of Richard Power’s the Overstory.",
    "time": "June 12—18",
    "images": [
      { "time": "5", "data": "1" },
      { "time": "20", "data": "2" },
      { "time": "30", "data": "3" },
      { "time": "49", "data": "4" },
      { "time": "71", "data": "5" },
      { "time": "76", "data": "6" },
      { "time": "83", "data": "7" },
      { "time": "96", "data": "8" },
      { "time": "122", "data": "9" },
      { "time": "142", "data": "10" },
      { "time": "159", "data": "11" },
      { "time": "167", "data": "12" }
    ],
    "texts": []
  }
];